title: Carina Fiedler
markdown: kramdown

t:
  en:
    home:
      name: "Home"
      url: "/"
    about:
      name: "About"
      url: "/about/en"
    cv:
      name: "CV"
      url: "/cv/en"
  de:
    home:
      name: "Home"
      url: "/de"
    about:
      name: "Über"
      url: "/about/de"
    cv:
      name: "CV"
      url: "/cv/de"

s:
  en:
    horse:
      name: "Do you want to know why horses are great?"
      url: "horse"
    maths:
      name: "Why I love Maths and Computer Science"
      url: "maths"
  de:
    horse:
      name: "Willst du wissen, was das Besondere an Pferden ist?"
      url: "horseDE"
    maths:
      name: "Was ich an Mathe und Informatik so liebe"
      url: "mathsDE"
