title: Carina Fiedler
markdown: kramdown

t:
  en:
    home:
      name: "Home"
      url: "/"
    about:
      name: "About"
      url: "/about/en"
    cv:
      name: "CV"
      url: "/cv/en"
  de:
    home:
      name: "Home"
      url: "/de"
    about:
      name: "Über"
      url: "/about/de"
    cv:
      name: "CV"
      url: "/cv/de"

s:
  en:
    horse:
      name: "Do you want to know why horses are great?"
      url: "horse/en"
    maths:
      name: "Why I love Maths and Computer Science"
      url: "maths/en"
  de:
    horse:
      name: "Willst du wissen, was das Besondere an Pferden ist?"
      url: "horse/de"
    maths:
      name: "Was ich an Mathe und Informatik so liebe"
      url: "maths/de"

p:
  en:
    ants: "View AntColonyOptimization on Github"
    messenger: "View EasyMessenger on Github"
  de:
    ants: "Sieh dir AntColonyOptimization auf Github an"
    messenger: "Sieh dir EasyMessenger auf Github an"
